notifications:
  email: false
matrix:
  include:
    - os: windows
      language: sh
      before_install:
        - choco install julia
      script:
        - julia --color=yes -e 'using InteractiveUtils; versioninfo(verbose=true)'
        - julia --color=yes --project=. -e 'using Pkg; Pkg.test()'
    - os: linux
      language: julia
      julia:
        - 1.0
